### ISSUE TITLE
Read passphrase from environment

### ISSUE THREAD

**Issue by aaperis** [neicnordic/crypt4gh#118]
As a developer 
I want to be able to supply the c4gh passphrase as an env variable
so that I can use the tool in scripts for automation.

**Comment by kjellp** [comment]
For decryption, encryption or both? For encryption, a temporary/one-time key could be considered as an option (as done in sda-cli)?

**Comment by aaperis** [comment]
> For decryption, encryption or both?

This is meant for both decryption and encryption when in the later the user supplies a private key along with a pub key.  

> For encryption, a temporary/one-time key could be considered as an option (as done in sda-cli)?

For encryption this is already how crypt4gh works if no private key is provided.
