### ISSUE TITLE
Encryption fails when private signing key is used

### ISSUE THREAD

**Issue by jbygdell** [neicnordic/crypt4gh#38]
**Describe the bug**

**To Reproduce**
```
crypt4gh encrypt -f test -p user2.pub.pem -s user1.sec.pem 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x613089]

goroutine 1 [running]:
github.com/neicnordic/crypt4gh/keys.ReadPrivateKey({0x6e67e0?, 0xc0000a8068?}, {0x0, 0x0, 0x0})
        /home/runner/work/crypt4gh/crypt4gh/keys/keys.go:97 +0x189
main.readPrivateKey({0x7ffff5c32f48, 0xd})
        /home/runner/work/crypt4gh/crypt4gh/main.go:117 +0x76
main.encryptOp({0x0, 0x0})
        /home/runner/work/crypt4gh/crypt4gh/main.go:321 +0x2ca
main.main()
        /home/runner/work/crypt4gh/crypt4gh/main.go:87 +0x495
```

**Expected behavior**
File should be encrypted and signed with users private key (user1.sec.pem )

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jbygdell** [comment]
This is the environment where it failed: https://github.com/neicnordic/sda-dashboard/pull/7/files

Although I can not replicate it with the current crypt4gh master branch.

**Comment by blankdots** [comment]
@jbygdell if we cannot replicate I propose we close this issue.
